In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
train = pd.read_csv("./data/train_FD001.txt", sep = " ", header = None).drop(columns=[26,27])

In [19]:
test = pd.read_csv("./data/test_FD001.txt", sep = " ", header = None).drop(columns=[26,27])

In [20]:
train.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [21]:
new_column_names = [
    "Engine_no",
    "Cycle_no",
    "Setting_1",
    "Setting_2",
    "Setting_3",
    "Fan_inlet_temperature",
    "LPC_outlet_temperature",
    "HPC_outlet_temperature",
    "LPT_outlet_temperature",
    "Fan_inlet_pressure",
    "Bypass_duct_pressure",
    "HPC_outlet_pressure",
    "Physical_fan_speed",
    "Physical_core_speed",
    "Engine_pressure_ratio",
    "HPC_outlet_static_pressure",
    "Fuel_flow_ratio",
    "Fan_speed",
    "Core_speed",
    "Bypass_ratio",
    "Burner_fuel_air_ratio",
    "Bleed_enthalpy",
    "Required_fan_speed",
    "Required_fan_conversion_speed",
    "High_pressure_cool_air_flow",
    "Low_pressure_cool_air_flow"
]

In [22]:
train.columns = new_column_names
test.columns = new_column_names

In [25]:
train_check = train[train["Engine_no"]==1]

In [26]:
train_check.tail()

,Engine_no,Cycle_no,Setting_1,Setting_2,Setting_3,Fan_inlet_temperature,LPC_outlet_temperature,HPC_outlet_temperature,LPT_outlet_temperature,Fan_inlet_pressure,...,Fuel_flow_ratio,Fan_speed,Core_speed,Bypass_ratio,Burner_fuel_air_ratio,Bleed_enthalpy,Required_fan_speed,Required_fan_conversion_speed,High_pressure_cool_air_flow,Low_pressure_cool_air_flow
187,1,188,-0.0067,0.0003,100.0,518.67,643.75,1602.38,1422.78,14.62,...,519.79,2388.23,8117.69,8.5207,0.03,396,2388,100.0,38.51,22.9588
188,1,189,-0.0006,0.0002,100.0,518.67,644.18,1596.17,1428.01,14.62,...,519.58,2388.33,8117.51,8.5183,0.03,395,2388,100.0,38.48,23.1127
189,1,190,-0.0027,0.0001,100.0,518.67,643.64,1599.22,1425.95,14.62,...,520.04,2388.35,8112.58,8.5223,0.03,398,2388,100.0,38.49,23.0675
190,1,191,-0.0000,-0.0004,100.0,518.67,643.34,1602.36,1425.77,14.62,...,519.57,2388.30,8114.61,8.5174,0.03,394,2388,100.0,38.45,23.1295
191,1,192,0.0009,-0.0000,100.0,518.67,643.54,1601.41,1427.20,14.62,...,520.08,2388.32,8110.93,8.5113,0.03,396,2388,100.0,38.48,22.9649

In [27]:
test_check = test[test["Engine_no"] == 1]

In [28]:
test_check.tail()

,Engine_no,Cycle_no,Setting_1,Setting_2,Setting_3,Fan_inlet_temperature,LPC_outlet_temperature,HPC_outlet_temperature,LPT_outlet_temperature,Fan_inlet_pressure,...,Fuel_flow_ratio,Fan_speed,Core_speed,Bypass_ratio,Burner_fuel_air_ratio,Bleed_enthalpy,Required_fan_speed,Required_fan_conversion_speed,High_pressure_cool_air_flow,Low_pressure_cool_air_flow
26,1,27,-0.0007,0.0001,100.0,518.67,642.08,1586.65,1400.31,14.62,...,521.82,2388.02,8127.24,8.4494,0.03,392,2388,100.0,38.87,23.3931
27,1,28,0.0022,0.0005,100.0,518.67,641.93,1594.25,1401.29,14.62,...,521.84,2388.07,8134.89,8.4470,0.03,392,2388,100.0,38.83,23.3502
28,1,29,0.0014,0.0001,100.0,518.67,641.95,1587.15,1398.11,14.62,...,522.39,2388.07,8133.13,8.4212,0.03,392,2388,100.0,39.02,23.3621
29,1,30,-0.0025,0.0004,100.0,518.67,642.79,1585.72,1400.97,14.62,...,521.78,2388.10,8134.79,8.4110,0.03,391,2388,100.0,39.09,23.4069
30,1,31,-0.0006,0.0004,100.0,518.67,642.58,1581.22,1398.91,14.62,...,521.79,2388.06,8130.11,8.4024,0.03,393,2388,100.0,38.81,23.3552