In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#File 01

df_train1 = pd.read_csv("./data/train_FD001.txt", sep = " ", header= None).drop(columns=[26,27])
df_test1 = pd.read_csv("./data/test_FD001.txt", sep = " ", header = None).drop(columns=[26,27])
df_rul1 = pd.read_csv("./data/RUL_FD001.txt", sep = " ", header = None).drop(columns=[1])

In [3]:
df_train1

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [4]:
df_test1

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,521.72,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,522.16,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,521.97,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,521.38,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,522.15,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,...,520.69,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974
13092,100,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,...,521.05,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771
13093,100,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,...,521.18,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051
13094,100,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,...,521.33,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699
13095,100,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,...,521.07,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855

In [5]:
df_rul1

      0
0   112
1    98
2    69
3    82
4    91
..  ...
95  137
96   82
97   59
98  117
99   20

[100 rows x 1 columns]

In [6]:
new_column_names = [
    "Engine_no",
    "Cycle_no",
    "Setting_1",
    "Setting_2",
    "Setting_3",
    "Fan_inlet_temperature",
    "LPC_outlet_temperature",
    "HPC_outlet_temperature",
    "LPT_outlet_temperature",
    "Fan_inlet_pressure",
    "Bypass_duct_pressure",
    "HPC_outlet_pressure",
    "Physical_fan_speed",
    "Physical_core_speed",
    "Engine_pressure_ratio",
    "HPC_outlet_static_pressure",
    "Fuel_flow_ratio",
    "Fan_speed",
    "Core_speed",
    "Bypass_ratio",
    "Burner_fuel_air_ratio",
    "Bleed_enthalpy",
    "Required_fan_speed",
    "Required_fan_conversion_speed",
    "High_pressure_cool_air_flow",
    "Low_pressure_cool_air_flow"
]

In [7]:
df_train1.columns = new_column_names
df_test1.columns = new_column_names

In [8]:
df_train1

,Engine_no,Cycle_no,Setting_1,Setting_2,Setting_3,Fan_inlet_temperature,LPC_outlet_temperature,HPC_outlet_temperature,LPT_outlet_temperature,Fan_inlet_pressure,...,Fuel_flow_ratio,Fan_speed,Core_speed,Bypass_ratio,Burner_fuel_air_ratio,Bleed_enthalpy,Required_fan_speed,Required_fan_conversion_speed,High_pressure_cool_air_flow,Low_pressure_cool_air_flow
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [9]:
df_test1

,Engine_no,Cycle_no,Setting_1,Setting_2,Setting_3,Fan_inlet_temperature,LPC_outlet_temperature,HPC_outlet_temperature,LPT_outlet_temperature,Fan_inlet_pressure,...,Fuel_flow_ratio,Fan_speed,Core_speed,Bypass_ratio,Burner_fuel_air_ratio,Bleed_enthalpy,Required_fan_speed,Required_fan_conversion_speed,High_pressure_cool_air_flow,Low_pressure_cool_air_flow
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,521.72,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,522.16,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,521.97,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,521.38,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,522.15,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,...,520.69,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974
13092,100,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,...,521.05,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771
13093,100,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,...,521.18,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051
13094,100,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,...,521.33,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699
13095,100,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,...,521.07,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855

In [10]:
df_train1.sample(5)

,Engine_no,Cycle_no,Setting_1,Setting_2,Setting_3,Fan_inlet_temperature,LPC_outlet_temperature,HPC_outlet_temperature,LPT_outlet_temperature,Fan_inlet_pressure,...,Fuel_flow_ratio,Fan_speed,Core_speed,Bypass_ratio,Burner_fuel_air_ratio,Bleed_enthalpy,Required_fan_speed,Required_fan_conversion_speed,High_pressure_cool_air_flow,Low_pressure_cool_air_flow
3824,19,49,-0.0029,0.0004,100.0,518.67,642.76,1589.66,1407.59,14.62,...,520.89,2388.14,8124.99,8.4381,0.03,393,2388,100.0,38.88,23.3476
8465,44,21,0.0026,-0.0001,100.0,518.67,642.27,1582.88,1400.56,14.62,...,521.91,2388.02,8147.44,8.4537,0.03,391,2388,100.0,39.11,23.4018
19671,96,120,-0.0026,0.0003,100.0,518.67,641.87,1584.11,1401.98,14.62,...,521.90,2388.09,8135.52,8.4136,0.03,393,2388,100.0,39.08,23.3331
1035,5,189,0.0005,-0.0004,100.0,518.67,643.18,1582.91,1411.05,14.62,...,521.53,2387.96,8163.51,8.4415,0.03,394,2388,100.0,38.79,23.3599
10923,55,137,-0.0002,0.0005,100.0,518.67,642.03,1595.69,1404.53,14.62,...,521.11,2388.07,8160.26,8.4335,0.03,395,2388,100.0,38.85,23.3662

In [11]:
df_train1['RUL_max'] = df_train1.groupby('Engine_no')['Cycle_no'].transform('max')
df_train1["RUL"] = df_train1["RUL_max"] - df_train1["Cycle_no"]

In [16]:
df_train1["RUL_max"].unique().mean()

212.07575757575756

In [13]:
a

NameError: name 'a' is not defined

In [ ]:
df_test1['RUL_max'] = df_test1.groupby('Engine_no')['Cycle_no'].transform('max')
df_test1["RUL"] = df_test1["RUL_max"] - df_test1["Cycle_no"]
df_test1.drop("RUL_max", axis = 1, inplace = True)

In [ ]:
x_train ,y_train = df_train1.drop(columns=['RUL']) , df_train1['RUL']

x_test, y_test = df_test1.drop(columns=['RUL']) , df_test1['RUL']

In [ ]:
from sklearn.metrics import r2_score  , mean_squared_error

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(x_train)

In [ ]:
r2_score(y_pred, y_train)

0.5071445119616631

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model2 = RandomForestRegressor()

In [ ]:
model2.fit(x_train, y_train)

RandomForestRegressor()

In [ ]:
y_pred = model2.predict(x_test)

In [ ]:
r2_score(y_pred, y_test)

-1.1691652071598786